# Generated by Django 4.0.1 on 2022-01-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['created'], 'verbose_name': 'Curso - Modulo', 'verbose_name_plural': 'Cursos - Modulos'},
        ),
        migrations.AddField(
            model_name='module',
            name='description',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
