# Generated by Django 4.0.1 on 2022-01-21 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_module_options_module_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='course',
        ),
        migrations.AddField(
            model_name='resource',
            name='class_video',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.video'),
            preserve_default=False,
        ),
    ]
