# Generated by Django 4.0.3 on 2022-04-05 15:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_blog_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='tutor_name',
            new_name='extra_txt',
        ),
        migrations.RemoveField(
            model_name='course',
            name='code_trip',
        ),
        migrations.RemoveField(
            model_name='course',
            name='tutor_text',
        ),
        migrations.AddField(
            model_name='course',
            name='authorized_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='authorized_user_course', to=settings.AUTH_USER_MODEL),
        ),
    ]
