# Generated by Django 4.0.3 on 2022-04-06 04:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_tutor_name_course_extra_txt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='shop_courses',
        ),
        migrations.RemoveField(
            model_name='user',
            name='initial_test_performed',
        ),
        migrations.CreateModel(
            name='ViewVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.video')),
            ],
            options={
                'ordering': ['-created', '-modified'],
                'get_latest_by': ('created',),
                'abstract': False,
            },
        ),
    ]
