# Generated by Django 4.0.3 on 2022-04-06 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_profileuser_shop_courses_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewvideo',
            name='course',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='api.course'),
            preserve_default=False,
        ),
    ]
