# Generated by Django 4.0.3 on 2022-04-06 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_viewvideo_course'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultcontest',
            name='calification',
        ),
        migrations.RemoveField(
            model_name='resultcontest',
            name='code_travel',
        ),
    ]
