# Generated by Django 4.0.3 on 2022-04-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_resultcontest_calification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='approved_courses',
            field=models.ManyToManyField(blank=True, related_name='user_aproved_courses', to='api.resultcontest'),
        ),
    ]
