# Generated by Django 4.0.3 on 2022-04-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_profileuser_approved_courses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='passing_score',
        ),
        migrations.AddField(
            model_name='course',
            name='description_promotional',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='file_promotional',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
