# Generated by Django 4.0.4 on 2022-05-03 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_course_passing_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
